export const styles = {
  pageCentered: {
    minHeight: '100vh',
    background: '#f4f5f7',
    fontFamily: 'system-ui, -apple-system, Segoe UI, Roboto, sans-serif',
    color: '#172b4d',
    display: 'flex',
    justifyContent: 'center',
    padding: '32px 16px',
  },
  welcomeInner: {
    width: '100%',
    maxWidth: 640,
  },
  title: {
    margin: '0 0 8px',
    fontSize: '1.6rem',
    fontWeight: 700,
  },
  subtitle: {
    margin: '0 0 24px',
    color: '#5e6c84',
    fontSize: '0.95rem',
  },
  card: {
    background: '#fff',
    borderRadius: 10,
    padding: '22px',
    boxShadow: '0 1px 3px rgba(9, 30, 66, 0.12)',
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  subHeading: {
    margin: '8px 0 0',
    fontSize: '0.95rem',
    fontWeight: 600,
  },
  sectionTitle: {
    margin: '0 0 10px',
    fontSize: '0.95rem',
    fontWeight: 700,
    color: '#172b4d',
  },
  envGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
    gap: 12,
  },
  envCardWrap: {
    position: 'relative',
  },
  envCard: {
    width: '100%',
    textAlign: 'left',
    padding: '16px 36px 16px 16px',
    border: '1px solid #dfe1e6',
    borderRadius: 8,
    background: '#fafbfc',
    cursor: 'pointer',
    transition: 'border-color 0.15s',
  },
  envMenuButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 28,
    height: 28,
    padding: 0,
    border: 'none',
    borderRadius: 4,
    background: 'transparent',
    color: '#5e6c84',
    fontSize: '1.1rem',
    lineHeight: 1,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  envDropdown: {
    position: 'absolute',
    top: 36,
    right: 8,
    zIndex: 20,
    minWidth: 160,
    background: '#fff',
    border: '1px solid #dfe1e6',
    borderRadius: 6,
    boxShadow: '0 4px 12px rgba(9, 30, 66, 0.15)',
    overflow: 'hidden',
  },
  envDeleteOption: {
    display: 'block',
    width: '100%',
    padding: '10px 14px',
    border: 'none',
    background: '#fff',
    color: '#de350b',
    fontSize: '0.85rem',
    fontWeight: 600,
    textAlign: 'left',
    cursor: 'pointer',
  },
  backToEnvironments: {
    marginTop: 14,
    padding: '8px 0',
    border: 'none',
    background: 'transparent',
    color: '#0052cc',
    fontSize: '0.85rem',
    fontWeight: 600,
    cursor: 'pointer',
    alignSelf: 'flex-start',
  },
  envName: {
    fontSize: '1rem',
    fontWeight: 700,
    marginBottom: 4,
  },
  envMeta: {
    fontSize: '0.8rem',
    color: '#5e6c84',
  },
  linkButton: {
    marginTop: 4,
    padding: 0,
    border: 'none',
    background: 'transparent',
    color: '#0052cc',
    fontSize: '0.85rem',
    fontWeight: 600,
    cursor: 'pointer',
  },
  envCreateButton: {
    alignSelf: 'flex-start',
    margin: 0,
    marginTop: 'auto',
    padding: 0,
    border: 'none',
    background: 'transparent',
    color: '#0052cc',
    fontSize: '0.85rem',
    fontWeight: 600,
    cursor: 'pointer',
  },
  label: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    fontSize: '0.75rem',
    fontWeight: 600,
    color: '#5e6c84',
  },
  input: {
    padding: '8px 10px',
    border: '1px solid #dfe1e6',
    borderRadius: 6,
    fontSize: '0.9rem',
    color: '#172b4d',
  },
  select: {
    padding: '8px 10px',
    border: '1px solid #dfe1e6',
    borderRadius: 6,
    fontSize: '0.85rem',
    background: '#fff',
    color: '#172b4d',
  },
  btnPrimary: {
    padding: '10px 14px',
    border: 'none',
    borderRadius: 6,
    background: '#0052cc',
    color: '#fff',
    fontWeight: 600,
    fontSize: '0.9rem',
    cursor: 'pointer',
  },
  btnSecondary: {
    padding: '10px 14px',
    border: '1px solid #dfe1e6',
    borderRadius: 6,
    background: '#fff',
    color: '#172b4d',
    fontWeight: 600,
    fontSize: '0.9rem',
    cursor: 'pointer',
  },
  btnSync: {
    width: '100%',
    padding: '14px',
    border: 'none',
    borderRadius: 8,
    background: '#00875a',
    color: '#fff',
    fontSize: '1rem',
    fontWeight: 700,
    cursor: 'pointer',
  },
  status: { margin: 0, fontSize: '0.85rem' },
  hint: { margin: 0, fontSize: '0.85rem', color: '#5e6c84' },

  appShell: {
    display: 'flex',
    flexDirection: 'column',
    height: '100vh',
    overflow: 'hidden',
    fontFamily: 'system-ui, -apple-system, Segoe UI, Roboto, sans-serif',
    color: '#172b4d',
    background: '#fff',
  },
  globalTopBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 20px',
    borderBottom: '1px solid #ebecf0',
    background: '#fff',
    flexShrink: 0,
  },
  topBarLeft: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 6,
  },
  envLabel: {
    fontSize: '0.9rem',
    color: '#42526e',
  },
  gearButton: {
    width: 40,
    height: 40,
    padding: 0,
    border: '1px solid #dfe1e6',
    borderRadius: 8,
    background: '#fafbfc',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  gearIcon: {
    width: 22,
    height: 22,
    objectFit: 'contain',
    display: 'block',
    pointerEvents: 'none',
  },
  splitRow: {
    display: 'flex',
    flex: 1,
    overflow: 'hidden',
  },
  leftPanel: {
    width: '34%',
    minWidth: 280,
    maxWidth: 420,
    borderRight: '1px solid #ebecf0',
    background: '#f4f5f7',
    overflowY: 'auto',
    padding: '16px',
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  leftSection: {
    background: '#fff',
    borderRadius: 8,
    padding: '14px',
    boxShadow: '0 1px 2px rgba(9, 30, 66, 0.08)',
    marginBottom: 8,
  },
  rightPanel: {
    flex: 1,
    background: '#f8fafc',
    overflowY: 'auto',
    padding: '20px',
  },
  summaryBox: {
    padding: '10px 12px',
    border: '1px solid #ebecf0',
    borderRadius: 6,
    background: '#fafbfc',
    fontSize: '0.82rem',
  },
  summarySection: { marginBottom: 12 },
  summaryTitle: { fontWeight: 700, marginBottom: 6, color: '#172b4d' },
  summaryEmpty: { color: '#5e6c84' },
  summaryList: { margin: 0, paddingLeft: 18, color: '#42526e' },
  summaryListItem: { marginBottom: 8 },
  summaryProjectLine: { fontWeight: 600 },
  summarySubList: { margin: '4px 0 0', paddingLeft: 16 },
  syncStatusLine: { margin: '8px 0 0', fontSize: '0.85rem', color: '#5e6c84' },
  syncLogConsole: {
    marginTop: 6,
    maxHeight: 180,
    overflowY: 'auto',
    background: '#fafbfc',
    border: '1px solid #ebecf0',
    borderRadius: 6,
    padding: '8px 10px',
    fontSize: '0.78rem',
    lineHeight: 1.45,
  },
  syncLogHeading: {
    margin: '10px 0 0',
    fontSize: '0.82rem',
    fontWeight: 600,
    color: '#42526e',
  },
  syncLogEntry: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'baseline',
    gap: '6px 8px',
    marginBottom: 8,
    paddingBottom: 8,
    borderBottom: '1px solid #ebecf0',
  },
  syncLogEntryLast: {
    marginBottom: 0,
    paddingBottom: 0,
    borderBottom: 'none',
  },
  syncLogBadge: {
    fontSize: '0.62rem',
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
    padding: '2px 6px',
    borderRadius: 3,
    flexShrink: 0,
  },
  syncLogBadgeOk: {
    background: '#e3fcef',
    color: '#006644',
  },
  syncLogBadgeError: {
    background: '#ffebe6',
    color: '#bf2600',
  },
  syncLogBadgeSkipped: {
    background: '#f4f5f7',
    color: '#5e6c84',
  },
  syncLogBadgeInfo: {
    background: '#deebff',
    color: '#0747a6',
  },
  syncLogMessage: {
    flex: '1 1 140px',
    color: '#172b4d',
    minWidth: 0,
  },
  syncLogTimestamp: {
    marginLeft: 'auto',
    fontSize: '0.72rem',
    color: '#97a0af',
    flexShrink: 0,
  },
  syncLogLine: {
    color: '#172b4d',
    marginBottom: 4,
  },
  syncLogLineMuted: {
    color: '#97a0af',
    fontStyle: 'italic',
  },

  viewerBlock: {
    marginBottom: 28,
  },
  viewerTitle: {
    margin: '0 0 12px',
    fontSize: '1.05rem',
    fontWeight: 700,
    paddingLeft: 10,
    borderLeft: '4px solid #dfe1e6',
  },
  viewerTitleTrello: {
    borderLeftColor: '#0079bf',
  },
  viewerTitleJira: {
    borderLeftColor: '#0052cc',
  },
  viewerTitleLink: {
    color: 'inherit',
  },
  viewerSelect: {
    width: '100%',
    maxWidth: 360,
    marginBottom: 16,
    padding: '10px 12px',
    border: '1px solid #dfe1e6',
    borderRadius: 6,
    fontSize: '0.9rem',
    background: '#fff',
  },
  placeholder: {
    color: '#5e6c84',
    fontSize: '0.9rem',
    padding: '24px 0',
  },
  kanbanRow: {
    display: 'flex',
    gap: 16,
    overflowX: 'auto',
    paddingBottom: 12,
    alignItems: 'flex-start',
  },
  kanbanColumn: {
    minWidth: 220,
    maxWidth: 260,
    flexShrink: 0,
    background: '#ebecf0',
    borderRadius: 8,
    overflow: 'hidden',
  },
  kanbanColumnHeader: {
    padding: '10px 12px',
    fontWeight: 700,
    fontSize: '0.85rem',
    background: '#dfe1e6',
    color: '#172b4d',
  },
  kanbanColumnBody: {
    padding: 10,
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    minHeight: 80,
    maxHeight: 350,
    overflowY: 'auto',
  },
  taskCard: {
    background: '#fff',
    borderRadius: 6,
    padding: '10px 12px',
    fontSize: '0.85rem',
    boxShadow: '0 1px 2px rgba(9, 30, 66, 0.12)',
    lineHeight: 1.4,
  },
  issueKey: {
    fontSize: '0.75rem',
    fontWeight: 700,
    color: '#0052cc',
    marginBottom: 4,
  },

  modalOverlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(9, 30, 66, 0.45)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    padding: 16,
  },
  modalCard: {
    background: '#fff',
    borderRadius: 10,
    width: '100%',
    maxWidth: 480,
    maxHeight: '90vh',
    overflowY: 'auto',
    padding: '20px',
    boxShadow: '0 8px 24px rgba(9, 30, 66, 0.2)',
  },
  modalHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  modalTitle: { margin: 0, fontSize: '1.15rem', fontWeight: 700 },
  modalClose: {
    border: 'none',
    background: 'transparent',
    fontSize: '1.5rem',
    cursor: 'pointer',
    color: '#5e6c84',
    lineHeight: 1,
  },
  modalForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  formDivider: {
    margin: '4px 0',
    border: 'none',
    borderTop: '1px solid #ebecf0',
  },

  // Rules summary in left panel
  rulesSummaryTop: {
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  rulesSummaryCount: {
    fontSize: '0.85rem',
    color: '#5e6c84',
    fontWeight: 700,
  },

  // Rules modal
  rulesModalCard: {
    background: '#fff',
    borderRadius: 12,
    width: '100%',
    maxWidth: 980,
    maxHeight: '90vh',
    overflowY: 'auto',
    padding: '20px',
    boxShadow: '0 8px 24px rgba(9, 30, 66, 0.2)',
  },
  rulesEditorModalCard: {
    maxWidth: 820,
  },
  rulesModalHeaderRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
    gap: 12,
  },
  rulesGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: 16,
  },
  newRuleTile: {
    height: 140,
    border: '2px dashed #dfe1e6',
    borderRadius: 12,
    background: '#fafbfc',
    cursor: 'pointer',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  newRulePlus: {
    width: 36,
    height: 36,
    borderRadius: 999,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: '1px solid #dfe1e6',
    background: '#fff',
    fontSize: '1.25rem',
    fontWeight: 800,
    color: '#0052cc',
  },
  newRuleText: {
    fontSize: '0.9rem',
    fontWeight: 700,
    color: '#172b4d',
  },
  ruleTileWrap: {
    position: 'relative',
  },
  ruleTile: {
    width: '100%',
    height: 140,
    border: '1px solid #dfe1e6',
    borderRadius: 12,
    background: '#fff',
    cursor: 'pointer',
    padding: 14,
    textAlign: 'left',
    overflow: 'hidden',
  },
  ruleTileName: {
    fontSize: '0.95rem',
    fontWeight: 800,
    color: '#172b4d',
    display: '-webkit-box',
    WebkitLineClamp: 3,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
    wordBreak: 'break-word',
  },
  ruleTileMenuButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 28,
    height: 28,
    border: 'none',
    borderRadius: 6,
    background: '#fafbfc',
    cursor: 'pointer',
    color: '#5e6c84',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '1.1rem',
    lineHeight: 1,
  },
  ruleTileMenu: {
    position: 'absolute',
    top: 44,
    right: 10,
    zIndex: 50,
    minWidth: 120,
    background: '#fff',
    border: '1px solid #dfe1e6',
    borderRadius: 8,
    overflow: 'hidden',
    boxShadow: '0 6px 18px rgba(9, 30, 66, 0.18)',
  },
  ruleTileDelete: {
    width: '100%',
    padding: '10px 12px',
    border: 'none',
    background: '#fff',
    cursor: 'pointer',
    textAlign: 'left',
    fontWeight: 700,
    color: '#de350b',
  },
  rulesEditor: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  directionToggle: {
    display: 'flex',
    gap: 4,
    padding: 4,
    borderRadius: 10,
    background: '#f4f5f7',
    border: '1px solid #dfe1e6',
  },
  directionToggleBtn: {
    flex: 1,
    padding: '10px 14px',
    border: 'none',
    borderRadius: 8,
    background: 'transparent',
    color: '#5e6c84',
    fontSize: '0.88rem',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'background 0.15s, color 0.15s, box-shadow 0.15s',
  },
  directionToggleBtnActive: {
    background: '#fff',
    color: '#0052cc',
    boxShadow: '0 1px 4px rgba(9, 30, 66, 0.14)',
  },
  rulesMappingRow: {
    display: 'grid',
    gridTemplateColumns: '1fr auto 1fr',
    gap: 14,
    alignItems: 'start',
  },
  rulesMappingCol: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    minWidth: 0,
  },
  rulesMappingColHeader: {
    fontSize: '0.68rem',
    fontWeight: 700,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: '#5e6c84',
    marginBottom: -4,
  },
  rulesMappingArrow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 32,
    fontSize: '1.35rem',
    fontWeight: 700,
    color: '#97a0af',
    userSelect: 'none',
  },
  rulesEditorButtons: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: 10,
    marginTop: 6,
  },
};
